### PR TITLE
Add note about where to find a maintained version

### PR DESCRIPTION
**Pull request by tsujigiri**
cc: @StefanGreffenius

### CODE REVIEW

**Review by StefanGreffenius — APPROVED** [review]
Thanks @tsujigiri

**Comment by hwartig** [comment]
@tsujigiri did you consider [transferring ownership](https://github.com/ComboStrikeHQ/ruby-apicalypse/settings) instead
Screenshot 2020-12-02 at 07 28 50

**Comment by tsujigiri** [comment]
@hwartig I didn't. @StefanGreffenius: we could also do that. WDYT?

**Comment by StefanGreffenius** [comment]
@tsujigiri Sounds good :+1:

**Comment by tsujigiri** [comment]
@StefanGreffenius You need to delete your fork for this to work.

**Comment by StefanGreffenius** [comment]
> @StefanGreffenius You need to delete your fork for this to work.

@tsujigiri Alright, done

**Comment by hwartig** [comment]
Kinda miss working with you guys 😘

**Pull request merged**
