### PR TITLE
Updating Doc example to work with IGDB v4

### PR DESCRIPTION
**Pull request by dustyjewett**

### CODE REVIEW

**Comment by tsujigiri** [comment]
Hey @dustyjewett!
Thanks you for your pull-request, but we are not really maintaining this anymore. Maybe @StefanGreffenius wants to? If not, feel free to just fork it and we'll add a link to your fork.

**Comment by StefanGreffenius** [comment]
Hey @dustyjewett,
Hey @tsujigiri :wave: 

> Maybe @StefanGreffenius wants to?

No sorry, no time left for this repository. 

> If not, feel free to just fork it and we'll add a link to your fork.

Sounds good to me as well :+1:

**Comment by dustyjewett** [comment]
This is just a doc change to go with the v3->v4 transition. No maintenance required other than accepting the PR.

**Review by StefanGreffenius — APPROVED** [review]
> This is just a doc change to go with the v3->v4 transition. No maintenance required other than accepting the PR.

alright :+1: (sorry for the late response)

**Comment by StefanGreffenius** [comment]
@tsujigiri Heyho, have now realized that this gem actually gets used by some people. I would like to continue maintaining it. Can this PR been merged and i just fork the project afterwards?

**Pull request merged**
